name: Run tests and upload coverage

on:
  push:
    branches:
      - main
      - codecov

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up go # for testing + installing siegfried-based PRONOM detection
        uses: actions/setup-go@v5

      - name: Install mdto.py and dependencies
        run: |
          go install github.com/richardlehane/siegfried/cmd/sf@latest
          sf -update
          pip install pytest pytest-cov .

      - name: Run tests
        run: pytest --cov=. --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
