name: Tests

# run tests whenever main gets a commit or PR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # this is the only distro available 🙃

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mdto.py and dependencies
        run: |
          pip install pytest # pytest ≠ project dep, so add it here
          pip install .

      - name: Run tests
        run: pytest
