name: Tests

# run tests whenever main gets a commit or PR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # ubuntu is the only distro available 🙃

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mdto.py and test dependencies
        run: |
          pip install pytest requests # pytest + requests ≠ project deps, so add them here
          pip install .

      - name: Run tests
        run: pytest
